# Server port
server.port=8081

# File Upload Limit Configuration (for Video files)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Local Directory to store survey videos
app.video.storage.path=./uploads/videos

# Local Directory to store review videos (premium feature)
app.upload.dir=uploads/review-videos

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=snapsagedb
spring.data.mongodb.auto-index-creation=true

# Error Traces
server.error.include-message=always
server.error.include-stacktrace=always

# Local Directory to store videos
app.video.storage.path=./uploads/videos

# JWT Configuration
app.jwtSecret=4D6250655368566D597133743677397A24432646294A404E635266556A586E32
app.jwtExpirationMs=86400000

# Optional Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG