# Server port
server.port=8082

# File Upload Limit Configuration (for Video files)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=snapsagedb
spring.data.mongodb.auto-index-creation=true

# Local Directory to store videos
app.video.storage.path=./uploads/videos

# JWT Configuration
app.jwtSecret=4D6250655368566D597133743677397A24432646294A404E635266556A586E32
app.jwtExpirationMs=86400000

# Optional Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
